CREATE DATABASE IF NOT EXISTS signoz_traces;
CREATE DATABASE IF NOT EXISTS signoz_metrics;
CREATE DATABASE IF NOT EXISTS signoz_logs;
CREATE DATABASE IF NOT EXISTS signoz_metadata;
CREATE DATABASE IF NOT EXISTS signoz_analytics;
CREATE DATABASE IF NOT EXISTS plausible_events_db;
