receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        max_request_body_size: 2097152
        cors:
          allowed_origins:
            - "https://app.nanko.dev"
            - "https://www.nanko.dev"
            - "https://app.preprod.nanko.dev"
            - "https://www.preprod.nanko.dev"
            - "http://localhost:*"
          allowed_headers:
            - "*"

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    send_batch_max_size: 10000
    send_batch_size: 10000
    timeout: 1s

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  clickhousetraces:
    datasource: tcp://signoz:${CLICKHOUSE_SIGNOZ_PASSWORD}@clickhouse:9000/signoz_traces
  signozclickhousemetrics:
    dsn: tcp://signoz:${CLICKHOUSE_SIGNOZ_PASSWORD}@clickhouse:9000/signoz_metrics
  clickhouselogsexporter:
    dsn: tcp://signoz:${CLICKHOUSE_SIGNOZ_PASSWORD}@clickhouse:9000/signoz_logs

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [signozclickhousemetrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouselogsexporter]
