services:
  mercure:
    image: dunglas/mercure
    restart: "no"
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins http://localhost:5173
    ports:
      - "3001:80"
