services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.1.2-alpine
    restart: unless-stopped
    volumes:
      - nanko-local-signoz-clickhouse:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  signoz-alertmanager:
    image: signoz/alertmanager:0.23.6
    restart: unless-stopped
    volumes:
      - nanko-local-signoz-alertmanager:/data

  signoz-query-service:
    image: signoz/query-service:0.55.1
    restart: unless-stopped
    volumes:
      - ../signoz/alerts:/root/config/alerts:ro
      - ../signoz/dashboards:/root/config/dashboards:ro
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=false
      - ALERTMANAGER_API_PREFIX=http://signoz-alertmanager:9093/api/
    depends_on:
      clickhouse:
        condition: service_healthy

  signoz-frontend:
    image: signoz/frontend:0.55.1
    restart: unless-stopped
    ports:
      - "43301:3301"
    depends_on:
      - signoz-query-service

  otel-collector:
    image: signoz/signoz-otel-collector:0.111.23
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "44317:4317"
      - "44318:4318"
    depends_on:
      clickhouse:
        condition: service_healthy

networks:
  default:
    name: local_default

volumes:
  nanko-local-signoz-clickhouse:
  nanko-local-signoz-alertmanager:
